// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-list-by-id",
    "version": "1"
  },
  "paths": {
    "/getProductsList": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.getProductsList",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};